name: CI/CD Pipeline 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub 
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Pull the Existing Docker Image 
      - name: Pull Existing Docker Image
        run: docker pull idkwhooo/krish-portfolio:latest

      # Step 4: Deploy to Vercel
      - name: Deploy to Vercel
        run: npx vercel --prod --token 8vQPJCeiOjCYbzTlWn8AfDhj
